apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tk8u415sb-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tk8u415sb-java-quarkus-gitops